import { Divider, Group, Space } from "@mantine/core";
import { RenderBountyCardList } from "layout/BountyCardList";
import { MainFilters } from "layout/MainFilters";
import { NewBountyButton } from "layout/NewBountyButton";
import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>GratzOverflow</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Group position="apart">
        <MainFilters />
        <NewBountyButton />
      </Group>
      <Space h="sm" />
      <Divider />
      <Space h="sm" />
      <RenderBountyCardList />
    </div>
  );
}
